export const loadProductsFromCSV = async () => {
  try {
    const products = [
{ srNo: 1, title: "5 Pack Family Soap ( Pack of 5 sell in 12 )", qty: 1, variantPrice: 39 },
{ srNo: 2, title: "5 Pack Family Soap ( Box )", qty: 1, variantPrice: 78 },
{ srNo: 3, title: "Diaper 24 Pack - S - Pack of 3", qty: 1, variantPrice: 44.4 },
{ srNo: 4, title: "Diaper 24 Pack - S - Baie of 6", qty: 1, variantPrice: 88.8 },
{ srNo: 5, title: "Diaper 24 Pack - M - Pack of 3", qty: 1, variantPrice: 44.4 },
{ srNo: 6, title: "Diaper 24 Pack - M - Baie of 6", qty: 1, variantPrice: 88.8 },
{ srNo: 7, title: "Diaper 24 Pack - L - Pack of 3", qty: 1, variantPrice: 44.4 },
{ srNo: 8, title: "Diaper 24 Pack - L - Baie of 6", qty: 1, variantPrice: 88.8 },
{ srNo: 9, title: "Diaper 24 Pack - XL - Pack of 3", qty: 1, variantPrice: 44.4 },
{ srNo: 10, title: "Diaper 24 Pack - XL - Baie of 6", qty: 1, variantPrice: 88.8 },
{ srNo: 11, title: "Wow Mosquito Coil (Box) ", qty: 1, variantPrice: 65 },
{ srNo: 12, title: "Wow Mosquito Coil (Pack of 12)", qty: 1, variantPrice: 14.4 },
{ srNo: 13, title: "Zebra Matches (Pack of 100)", qty: 1, variantPrice: 7.5 },
{ srNo: 14, title: "Cake Break Donut Cake 24 pcs", qty: 1, variantPrice: 22 },
{ srNo: 15, title: "Porleo Donut Cake 24 pcs", qty: 1, variantPrice: 22 },
{ srNo: 16, title: "Cake Break Bar Kek 24 pcs", qty: 1, variantPrice: 22 },
{ srNo: 17, title: "Porleo Chocolate Cake 24 pcs", qty: 1, variantPrice: 22 },
{ srNo: 18, title: "WOW Toilet Paper (Pack of 12)", qty: 1, variantPrice: 22 },
{ srNo: 19, title: "Tautai Tomato 8 Pack", qty: 1, variantPrice: 22.5 },
{ srNo: 20, title: "Tautai Oil 8 Pack", qty: 1, variantPrice: 23.5 },
{ srNo: 21, title: "Rice Crackers 60g Pack of 10s", qty: 1, variantPrice: 22 },
{ srNo: 22, title: "ABC Powder 9 KG ( Pack of 6 - BrIlliant White )", qty: 1, variantPrice: 49 },
{ srNo: 23, title: "ABC Powder 9 KG ( Pack of 6 - Bright Color )", qty: 1, variantPrice: 49 },
{ srNo: 24, title: "ABC Powder 3 KG (Pack of 6 - BrIlliant White)", qty: 1, variantPrice: 18 },
{ srNo: 25, title: "ABC Powder 3 KG (Pack of 6 - Whites & Color)", qty: 1, variantPrice: 18 },
{ srNo: 26, title: "ABC Powder 3 KG (Pack of 6 - Bright Color)", qty: 1, variantPrice: 18 },
{ srNo: 27, title: "Baby Diaper Pack of 6 - Small", qty: 1, variantPrice: 88.8 },
{ srNo: 28, title: "Baby Diaper Pack of 6 - Medium", qty: 1, variantPrice: 88.8 },
{ srNo: 29, title: "Baby Diaper Pack of 6 - Large", qty: 1, variantPrice: 88.8 },
{ srNo: 30, title: "Baby Diaper Pack of 6 - Extra Large", qty: 1, variantPrice: 88.8 },
{ srNo: 31, title: "Liquid Food Colouring 150g (Pack of 6)", qty: 1, variantPrice: 69 },
{ srNo: 32, title: "Baking Powder 2KG (Pack of 8)", qty: 1, variantPrice: 30 },
{ srNo: 33, title: "Bread Improver (10 KG) (Pack of 20)", qty: 1, variantPrice: 102 },
{ srNo: 34, title: "Cake Mix (10 KG) - Chocolate", qty: 1, variantPrice: 110 },
{ srNo: 35, title: "Cake Mix (10 KG) - Chocolate Sponge", qty: 1, variantPrice: 115 },
{ srNo: 36, title: "Cake Mix (10 KG) - Vanilla", qty: 1, variantPrice: 110 },
{ srNo: 37, title: "Cake Mix (10 KG) - Vanilla Sponge", qty: 1, variantPrice: 105 },
{ srNo: 38, title: "Topping Sauces (Pack of 6)", qty: 1, variantPrice: 17 },
{ srNo: 39, title: "Whipped Cream Powder (1KG)", qty: 1, variantPrice: 30 },
{ srNo: 40, title: "White Papaya (Pau Esi) 5pkts", qty: 1, variantPrice: 42.5 },
{ srNo: 41, title: "Black Plum 5pkts", qty: 1, variantPrice: 44 },
{ srNo: 42, title: "Red Mango (Pau Mango)", qty: 1, variantPrice: 40 },
{ srNo: 43, title: "Red Plum (Lolly Saiga) 5pkts", qty: 1, variantPrice: 32.5 },
{ srNo: 44, title: "Red Peach (Monkey Ball) 5pkts", qty: 1, variantPrice: 32.5 },
{ srNo: 45, title: "ABC Powder 1.5 KG (Pack of 12 - Brilliant White)", qty: 1, variantPrice: 9 },
{ srNo: 46, title: "ABC Powder 1.5 KG (Pack of 12 - Whites & Color)", qty: 1, variantPrice: 9 },
{ srNo: 47, title: "ABC Powder 1.5 KG (Pack of 12 - Automat Lavender Freshness)", qty: 1, variantPrice: 9 },
{ srNo: 48, title: "Schick Extreme 3  4pcs (Pack of 5)", qty: 1, variantPrice: 20 },
{ srNo: 49, title: "Longkou Vermicelli ( Pack of 10 )", qty: 1, variantPrice: 20 },
{ srNo: 50, title: "Longkou Vermicelli ( Bag of 50 )", qty: 1, variantPrice: 95 },
{ srNo: 51, title: "Tautai Tomato 8 Pack", qty: 1, variantPrice: 15 },
{ srNo: 52, title: "Tautai Oil 8 Pack", qty: 1, variantPrice: 15 },
{ srNo: 53, title: "Bebeto Gumball 25g (Pack of 3)", qty: 1, variantPrice: 30 },
{ srNo: 54, title: "Bebeto Super Long Gum (Pack of 24)", qty: 1, variantPrice: 45 },
{ srNo: 55, title: "Bebeto Moji Lollipop with Stand (120 Pc)", qty: 1, variantPrice: 52 },
{ srNo: 56, title: "Bebeto Sour Blast (150 Pc)", qty: 1, variantPrice: 30 },
{ srNo: 57, title: "Bebeto Cobra (2KG)", qty: 1, variantPrice: 33 },
{ srNo: 58, title: "Bebeto Tongue (1KG) (Pack of 2)", qty: 1, variantPrice: 28 },
{ srNo: 59, title: "Panpan 35g - Original - Box of 50", qty: 1, variantPrice: 58 },
{ srNo: 60, title: "Panpan 35g - Original - Pack of 25", qty: 1, variantPrice: 31 },
{ srNo: 61, title: "Panpan 35g - Cheese - Box of 50", qty: 1, variantPrice: 58 },
{ srNo: 62, title: "Panpan 35g - Cheese - Pack of 25", qty: 1, variantPrice: 31 },
{ srNo: 63, title: "Panpan 35g - Sour Cream & Onion - Box of 50", qty: 1, variantPrice: 58 },
{ srNo: 64, title: "Panpan 35g - Sour Cream & Onion - Pack of 25", qty: 1, variantPrice: 31 },
{ srNo: 65, title: "Panpan 35g - BBQ - Box of 50", qty: 1, variantPrice: 58 },
{ srNo: 66, title: "Panpan 35g - BBQ - Pack of 25", qty: 1, variantPrice: 31 },
{ srNo: 67, title: "Panpan 35g - Tomato - Box of 50", qty: 1, variantPrice: 58 },
{ srNo: 68, title: "Panpan 35g - Tomato -  Pack of 25", qty: 1, variantPrice: 31 },
{ srNo: 69, title: "Panpan 45g - Original - Box of 48", qty: 1, variantPrice: 105.6 },
{ srNo: 70, title: "Panpan 45g -  Original - Pack of 12", qty: 1, variantPrice: 27.6 },
{ srNo: 71, title: "Panpan 45g - Cheese - Box of 48", qty: 1, variantPrice: 105.6 },
{ srNo: 72, title: "Panpan 45g -  Cheese - Pack of 12", qty: 1, variantPrice: 27.6 },
{ srNo: 73, title: "Panpan 45g - Sour Cream & Onion - Box of 48", qty: 1, variantPrice: 105.6 },
{ srNo: 74, title: "Panpan 45g - Sour Cream & Onion - Pack of 12", qty: 1, variantPrice: 27.6 },
{ srNo: 75, title: "Panpan 45g - BBQ - Box of 48", qty: 1, variantPrice: 105.6 },
{ srNo: 76, title: "Panpan 45g - BBQ	- Pack of 12", qty: 1, variantPrice: 27.6 },
{ srNo: 77, title: "Panpan 45g - Tomato - Box of 48", qty: 1, variantPrice: 105.6 },
{ srNo: 78, title: "Panpan 45g - Tomato - Pack of 12", qty: 1, variantPrice: 27.6 },
{ srNo: 79, title: "Panpan 110g - Original - Box of 24 Pcs", qty: 1, variantPrice: 96 },
{ srNo: 80, title: "Panpan 110g - Original - Pack of 12", qty: 1, variantPrice: 48 },
{ srNo: 81, title: "Panpan 110g - Cheese - Box of 24 Pcs", qty: 1, variantPrice: 96 },
{ srNo: 82, title: "Panpan 110g - Cheese - Pack of 12", qty: 1, variantPrice: 48 },
{ srNo: 83, title: "Panpan 110g - Sour Cream & Onion - Box of 24 Pcs", qty: 1, variantPrice: 96 },
{ srNo: 84, title: "Panpan 110g - Sour Cream & Onion - Pack of 12", qty: 1, variantPrice: 48 },
{ srNo: 85, title: "Panpan 110g - BBQ - Box of 24 Pcs", qty: 1, variantPrice: 96 },
{ srNo: 86, title: "Panpan 110g - BBQ - Pack of 12", qty: 1, variantPrice: 48 },
{ srNo: 87, title: "Panpan 110g - Tomato - Box of 24 Pcs", qty: 1, variantPrice: 96 },
{ srNo: 88, title: "Panpan 110g - Tomato - Pack of 12", qty: 1, variantPrice: 48 },
{ srNo: 89, title: "Hair Gel 500ml (Pack of 12 - Normal)", qty: 1, variantPrice: 72 },
{ srNo: 90, title: "Hair Gel 500ml (Pack of 12 - Ultra Strong)", qty: 1, variantPrice: 72 },
{ srNo: 91, title: "Hair Gel 500ml (Pack of 12 - Wet & Strong)", qty: 1, variantPrice: 72 },
{ srNo: 92, title: "Hair Gel 500ml (Pack of 12 - Wet)", qty: 1, variantPrice: 72 },
{ srNo: 93, title: "Hair Shower Gel 725g (Pack of 12 - Grape & Lavender)", qty: 1, variantPrice: 72 },
{ srNo: 94, title: "Hair Shower Gel 725g (Pack of 12 - Honey & Milk)", qty: 1, variantPrice: 72 },
{ srNo: 95, title: "Hair Shower Gel 725g (Pack of 12 - Raspberry & Rose Petal)", qty: 1, variantPrice: 72 },
{ srNo: 96, title: "Hair Shampoo 725g (Pack of 12 - Honey Extract)", qty: 1, variantPrice: 78 },
{ srNo: 97, title: "Hair Shampoo 725g (Pack of 12 - Egg Protein)", qty: 1, variantPrice: 78 },
{ srNo: 98, title: "Hair Shampoo 725g (Pack of 12 - Garlic Extract)", qty: 1, variantPrice: 78 },
{ srNo: 99, title: "Hair Shampoo 725g (Pack of 12 - Olive Oil Extract)", qty: 1, variantPrice: 78 },
{ srNo: 100, title: "Hair Shampoo 725g (Pack of 12 - Henna Extract)", qty: 1, variantPrice: 78 },
{ srNo: 101, title: "Hair Shampoo 725g (Pack of 12 - Argan Oil)", qty: 1, variantPrice: 78 },
{ srNo: 102, title: "Hair Shampoo 725g (Pack of 12 - Mint Extract)", qty: 1, variantPrice: 78 },
{ srNo: 103, title: "Hair Shampoo 725g (Pack of 12 - Normal Hair Bio Protein)", qty: 1, variantPrice: 78 },
{ srNo: 104, title: "Hair Shampoo 725g (Pack of 12 - Greasy Hair Bio Protein)", qty: 1, variantPrice: 78 },
{ srNo: 105, title: "Hair Shampoo 725g (Pack of 12 - Falling Hair Bio Protein)", qty: 1, variantPrice: 78 },
{ srNo: 106, title: "Hair Shampoo 725g (Pack of 12 - Dry & Damaged Hair Bio Protein)", qty: 1, variantPrice: 78 },
{ srNo: 107, title: "Hair Shampoo 725g (Pack of 12 - Coloured Hair Bio Protein)", qty: 1, variantPrice: 78 },
{ srNo: 108, title: "Hair Shampoo 725g (Pack of 12 - 2 in 1 All Hair Type Bio Protein)", qty: 1, variantPrice: 78 },
{ srNo: 109, title: "Hair Shampoo 725g (Pack of 12 - 2 in 1 Hair Type Bio Protein)", qty: 1, variantPrice: 78 },
{ srNo: 110, title: "Hair Conditioner 725g (Pack of 12 - Olive Oil Extract)", qty: 1, variantPrice: 46.9 },
{ srNo: 111, title: "Hair Conditioner 725g (Pack of 12 - Normal Hair Bio Protein)", qty: 1, variantPrice: 46.9 },
{ srNo: 112, title: "ABC Window Cleaner 500ml (Pack of 12 - Normal)", qty: 1, variantPrice: 66 },
{ srNo: 113, title: "ABC Window Cleaner 500ml (Pack of 12 - Lemon Freshness)", qty: 1, variantPrice: 66 },
{ srNo: 114, title: "ABC All Purpose Floor Cleaner 900ml (Pack of 14 - Pink Bouquet)", qty: 1, variantPrice: 84 },
{ srNo: 115, title: "ABC All Purpose Floor Cleaner 900ml (Pack of 14 - Spring Passion)", qty: 1, variantPrice: 84 },
{ srNo: 116, title: "ABC All Purpose Floor Cleaner 900ml (Pack of 14 - Magic Garden)", qty: 1, variantPrice: 84 },
{ srNo: 117, title: "ABC All Purpose Floor Cleaner 900ml (Pack of 14 - Purple Flowers)", qty: 1, variantPrice: 84 },
{ srNo: 118, title: "ABC Thick Bleach 900ml (Pack of 9 - Mountain Freshness)", qty: 1, variantPrice: 62.1 },
{ srNo: 119, title: "ABC Thick Bleach 900ml (Pack of 9 - Power of Hygiene)", qty: 1, variantPrice: 62.1 },
{ srNo: 120, title: "ABC Thick Bleach 900ml (Pack of 9 - Pure White)", qty: 1, variantPrice: 62.1 },
{ srNo: 121, title: "ABC Thick Bleach 900ml (Pack of 9 - Lemon)", qty: 1, variantPrice: 62.1 },
{ srNo: 122, title: "ABC Thick Bleach 900ml (Pack of 9 - Carbonate)", qty: 1, variantPrice: 62.1 },
{ srNo: 123, title: "ABC Bleach 1L (Pack of 9 - Spring)", qty: 1, variantPrice: 45 },
{ srNo: 124, title: "ABC Bleach 1L (Pack of 9 - Pure White)", qty: 1, variantPrice: 45 },
{ srNo: 125, title: "ABC Bleach 1L (Pack of 9 - Lavendar)", qty: 1, variantPrice: 45 },
{ srNo: 126, title: "ABC Krem Cleaner (Jif) 500g (Pack of 20 - Lemon)", qty: 1, variantPrice: 98 },
{ srNo: 127, title: "ABC Krem Cleaner (Jif) 500g (Pack of 20 - Ammonia)", qty: 1, variantPrice: 98 },
{ srNo: 128, title: "ABC Spray & Wipe (Kitchen) 750ml (Pack of 20)", qty: 1, variantPrice: 140 },
{ srNo: 129, title: "ABC Spray & Wipe (Bath) 750ml (Pack of 20)", qty: 1, variantPrice: 140 },
{ srNo: 130, title: "ABC Dishwashing Liquid 500g (Pack of 12 - Power)", qty: 1, variantPrice: 54 },
{ srNo: 131, title: "ABC Dishwashing Liquid 500g (Pack of 12 - Lemon)", qty: 1, variantPrice: 54 },
{ srNo: 132, title: "ABC Dishwashing Liquid 500g (Pack of 12 - Apple)", qty: 1, variantPrice: 54 },
{ srNo: 133, title: "ABC Softener 2L (Downy) (Pack of 6 - Sultan)", qty: 1, variantPrice: 72 },
{ srNo: 134, title: "ABC Softener 2L (Downy) (Pack of 6 - Ocean Glamour)", qty: 1, variantPrice: 72 },
{ srNo: 135, title: "ABC Softener 2L (Downy) (Pack of 6 - Camellia Love)", qty: 1, variantPrice: 72 },
{ srNo: 136, title: "ABC Softener 2L (Downy) (Pack of 6 - Rose Passion)", qty: 1, variantPrice: 72 },
{ srNo: 137, title: "ABC Softener 2L (Downy) (Pack of 6 - Lavender Peace)", qty: 1, variantPrice: 72 },
{ srNo: 138, title: "ABC Softener 1L (Downy) (Pack of 6 - Ocean Glamour)", qty: 1, variantPrice: 42 },
{ srNo: 139, title: "ABC Softener 1L (Downy) (Pack of 6 - Camellia Love)", qty: 1, variantPrice: 42 },
{ srNo: 140, title: "ABC Softener 1L (Downy) (Pack of 6 - Rose Passion)", qty: 1, variantPrice: 42 },
{ srNo: 141, title: "ABC Softener 1L (Downy) (Pack of 6 - Lavender Peace)", qty: 1, variantPrice: 42 },
{ srNo: 142, title: "ABC Softener 1L (Downy) (Pack of 6 - Sultan)", qty: 1, variantPrice: 42 },
{ srNo: 143, title: "ABC Laundry Liquid 3L (Pack of 6 - Black & Dark Laundry)", qty: 1, variantPrice: 135 },
{ srNo: 144, title: "ABC Laundry Liquid 3L (Pack of 6 - Colour Laundry)", qty: 1, variantPrice: 135 },
{ srNo: 145, title: "ABC Laundry Liquid 3L (Pack of 6 - Delicate & Wooly Laundry)", qty: 1, variantPrice: 135 },
{ srNo: 146, title: "ABC Laundry Liquid 1.5L (Pack of 9 - White Laundry)", qty: 1, variantPrice: 108 },
{ srNo: 147, title: "ABC Laundry Liquid 1.5L (Pack of 9 - Baby Laundry)", qty: 1, variantPrice: 108 },
{ srNo: 148, title: "ABC Laundry Liquid 1.5L (Pack of 9 - Colour Laundry)", qty: 1, variantPrice: 108 },
{ srNo: 149, title: "ABC Laundry Liquid 1.5L (Pack of 9 - Black & Dark Laundry)", qty: 1, variantPrice: 108 },
{ srNo: 150, title: "ABC Laundry Liquid 1.5L (Pack of 9 - Delicate & Wooly Laundry)", qty: 1, variantPrice: 108 },
{ srNo: 151, title: "Dalan Gift Set 1", qty: 1, variantPrice: 172 },
{ srNo: 152, title: "Dalan Gift Set 2", qty: 1, variantPrice: 172 },
{ srNo: 153, title: "Dalan Gift Set  3 - Pack of 3", qty: 1, variantPrice: 48 },
{ srNo: 154, title: "Dalan Body Oil 250ml (Pack of 6)", qty: 1, variantPrice: 84 },
{ srNo: 155, title: "Dalan d'Olive Conditioner 250ml (Pack of 6 - Color Protection)", qty: 1, variantPrice: 54 },
{ srNo: 156, title: "Dalan d'Olive Conditioner 250ml (Pack of 6 - Volumizing)", qty: 1, variantPrice: 54 },
{ srNo: 157, title: "Dalan d'Olive Conditioner 250ml (Pack of 6 - Repairing)", qty: 1, variantPrice: 54 },
{ srNo: 158, title: "Dalan Shower Gel 400ml (Pack of 6 - Magnolia)", qty: 1, variantPrice: 42 },
{ srNo: 159, title: "Dalan Shower Gel 400ml (Pack of 6 - Olive Oil)", qty: 1, variantPrice: 42 },
{ srNo: 160, title: "Dalan Shower Gel 400ml (Pack of 6 - Peach Blossom)", qty: 1, variantPrice: 42 },
{ srNo: 161, title: "Dalan Shampoo 400ml (Pack of 6 - Color Protection)", qty: 1, variantPrice: 60 },
{ srNo: 162, title: "Dalan Shampoo 400ml (Pack of 6 - Volumizing)", qty: 1, variantPrice: 60 },
{ srNo: 163, title: "Dalan Shampoo 400ml (Pack of 6 - Repairing)", qty: 1, variantPrice: 60 },
{ srNo: 164, title: "Dalan Hand & Body Cream - Pack of 6", qty: 1, variantPrice: 18 },
{ srNo: 165, title: "Dalan Olive Massage & Anti Cellulite Soap (Pack of 12)", qty: 1, variantPrice: 36 },
{ srNo: 166, title: "Dalan d'Olive Soap (Pack of 12)", qty: 1, variantPrice: 26.4 },
{ srNo: 167, title: "Dalan Derma-Cream Soap (Pack of 12)", qty: 1, variantPrice: 20.4 },
{ srNo: 168, title: "Covex Antibacterial Soap 115g (36pcs) - Active Protection", qty: 1, variantPrice: 54 },
{ srNo: 169, title: "Covex Antibacterial Soap 115g (36pcs) - Cool Protection", qty: 1, variantPrice: 54 },
{ srNo: 170, title: "Covex Antibacterial Soap 115g (36pcs) - Fresh Protection", qty: 1, variantPrice: 54 },
{ srNo: 171, title: "Dalan Roxy Soap 6 Pack (72 Pc) - Green Apple", qty: 1, variantPrice: 44.4 },
{ srNo: 172, title: "Dalan Roxy Soap 6 Pack (72 Pc) - Jasmine", qty: 1, variantPrice: 44.4 },
{ srNo: 173, title: "Dalan Roxy Soap 6 Pack (72 Pc) - Lavender", qty: 1, variantPrice: 44.4 },
{ srNo: 174, title: "Dalan Roxy Soap 6 Pack (72 Pc) - Lemon", qty: 1, variantPrice: 44.4 },
{ srNo: 175, title: "Dalan Roxy Soap 6 Pack (72 Pc) - Rose", qty: 1, variantPrice: 44.4 },
{ srNo: 176, title: "Dalan Roxy Soap 5 Pack (60 Pc) - Green Apple", qty: 1, variantPrice: 37.2 },
{ srNo: 177, title: "Dalan Roxy Soap 5 Pack (60 Pc) - Jasmine", qty: 1, variantPrice: 37.2 },
{ srNo: 178, title: "Dalan Roxy Soap 5 Pack (60 Pc) - Rose", qty: 1, variantPrice: 37.2 },
{ srNo: 179, title: "Dalan Roxy Soap 5 Pack (60 Pc) - Violet", qty: 1, variantPrice: 37.2 },
{ srNo: 180, title: "Dalan Nancy Soap 5 Pack (60 Pc) - Water Lily", qty: 1, variantPrice: 37.2 },
{ srNo: 181, title: "Dalan Nancy Soap 5 Pack (60 Pc) - Lilac", qty: 1, variantPrice: 37.2 },
{ srNo: 182, title: "Dalan Nancy Soap 5 Pack (60 Pc) - Lily of the Vally", qty: 1, variantPrice: 37.2 },
{ srNo: 183, title: "Citron Bar Soap 900g - Antibacterial - Box of 16 pieces", qty: 1, variantPrice: 104 },
{ srNo: 184, title: "Citron Bar Soap 900g - Classic - Box of 16 pieces", qty: 1, variantPrice: 104 },
{ srNo: 185, title: "Citron Bar Soap 900g - Antibacterial - Pack of 4", qty: 1, variantPrice: 26 },
{ srNo: 186, title: "Citron Bar Soap 900g - Classic - Pack of 4", qty: 1, variantPrice: 26 },
      // Add your actual products here
    ];
    
    return products;
  } catch (error) {
    console.error('Error loading products:', error);
    return [];
  }
}; 